version: '3.8'

services:
  cli:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: yourkaya
      POSTGRES_PASSWORD: yourkaya
      POSTGRES_DB: yourkaya
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  db: ~
